---
# tasks file for ajsalminen.drupal_basic

- name: Set wp_new_site_name
  set_fact:
    wp_new_site_name: "{{ synced_wordpress.new_site_name|default(wordpress_db.site_name) ~ local_test_environment|default('') }}"
  when: site_name != '000-default'

- name: Find out if content sync is enabled
  set_fact:
    do_site_content_sync: "{{ synced_wordpress is defined and (site_content_sync_sites[site_name]|default(false) or site_content_sync|default(false)) }}"

- name: Replace site name
  shell: /usr/local/bin/wp --allow-root search-replace --network --url={{wordpress_db.site_name}} --skip-columns=guid {{wordpress_db.site_name}} {{wp_new_site_name}} chdir={{wordpress_webroot}}
  when: do_site_content_sync|bool and wordpress_db.site_name is defined and wordpress_db.site_name != wp_new_site_name

- name: Remove Wordpress role capabilities
  shell: >
    /usr/local/bin/wp --allow-root --url="http://{{ wp_new_site_name }}" cap remove {{item.key}} {{item.value | join(" ")}}
    chdir={{wordpress_webroot}}
  with_dict: synced_wordpress_role_capabilities_removed
  register: result
  changed_when: result.stdout.find('Removed 0 capabilities') == -1
